// Decompiled with JetBrains decompiler
// Type: com.glu.game.eAchievementID
// Assembly: Guitar Hero 5, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 86E366E3-F44F-4C53-89BA-5BEFDCC09A14
// Assembly location: C:\Users\Admin\Desktop\RE\Guitar_Hero_5_v1.2\Guitar Hero 5.dll

#nullable disable
namespace com.glu.game
{
  public enum eAchievementID
  {
    ACHIEVEMENT_COMPLETE_SONG_GUITAR,
    ACHIEVEMENT_TWO_HUNDRED_NOTES,
    ACHIEVEMENT_COMPLETE_SAN_FRANCISCO,
    ACHIEVEMENT_COMPLETE_NEW_YORK,
    ACHIEVEMENT_COMPLETE_CAIRO,
    ACHIEVEMENT_PERFECT_GUITAR,
    ACHIEVEMENT_PERFECT_BASS,
    ACHIEVEMENT_PERFECT_DRUMS,
    ACHIEVEMENT_FIVE_STARS_ONE_SONG,
    ACHIEVEMENT_FIVE_STARS_FOUR_SONGS,
    ACHIEVEMENT_FIVE_STARS_GUITAR_EXPERT,
    ACHIEVEMENT_FIVE_STARS_GUITAR_EXP_4_SONGS,
    ACHIEVEMENT_FIVE_STARS_BASS_EXPERT,
    ACHIEVEMENT_FIVE_STARS_BASS_EXP_4_SONGS,
    ACHIEVEMENT_FIVE_STARS_DRUMS_EXPERT,
    ACHIEVEMENT_FIVE_STARS_DRUMS_EXP_4_SONGS,
    ACHIEVEMENT_PERFECT_ON_EXPERT,
    ACHIEVEMENT_COMPLETE_TWO_SF,
    ACHIEVEMENT_COMPLETE_TWO_NEW_YORK,
    ACHIEVEMENT_COMPLETE_TWO_CAIRO,
    achievementID_INVALID,
  }
}
